//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Modules.Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Modules.Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddItemButtonText {
            get {
                return ResourceManager.GetString("AddItemButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string AddItemViewDisplayName {
            get {
                return ResourceManager.GetString("AddItemViewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string AddItemViewType {
            get {
                return ResourceManager.GetString("AddItemViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close folder.
        /// </summary>
        public static string CloseFolderCommandText {
            get {
                return ResourceManager.GetString("CloseFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close folder.
        /// </summary>
        public static string CloseFolderCommandToolTip {
            get {
                return ResourceManager.GetString("CloseFolderCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ExplorerViewModel_ExplorerViewModel_Explorer {
            get {
                return ResourceManager.GetString("ExplorerViewModel_ExplorerViewModel_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolderCommandText {
            get {
                return ResourceManager.GetString("OpenFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolderCommandToolTip {
            get {
                return ResourceManager.GetString("OpenFolderCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ViewExplorerCommandText {
            get {
                return ResourceManager.GetString("ViewExplorerCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View folder explorer.
        /// </summary>
        public static string ViewExplorerCommandToolTip {
            get {
                return ResourceManager.GetString("ViewExplorerCommandToolTip", resourceCulture);
            }
        }
    }
}
